### ISSUE TITLE
Data inconsistency

### ISSUE THREAD

**Issue by alireza-rezaee** [smajidi/Iran-COVID-19-Data#1]
<div dir="rtl">

سلام
در حال مشاهده [فایل داده ها](https://github.com/smajidi/Iran-COVID-19-Data/blob/66eb22d569ae7da3aa2670b0c6720f969dc42142/Iran_Dailly_Covid19_Stat.csv) متوجه ناهماهنگی با گزارش خبری روابط عمومی وزارت بهداشت شدم.

این سطر را با [گزارش هشتم اسفند](https://behdasht.gov.ir/%D8%A7%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B4%D9%86%D8%A7%D8%B3%D8%A7%DB%8C%DB%8C-106-%D8%A8%DB%8C%D9%85%D8%A7%D8%B1-%D8%AC%D8%AF%DB%8C%D8%AF-%DA%A9%D9%88%D9%88%DB%8C%D8%AF19-%D8%AF%D8%B1-%DA%A9%D8%B4%D9%88%D8%B1) روابط عمومی مقایسه کنید.

</div>

``` 98/12/08,2/27/20,248,109,168,54,0,26,7,NA,NA,NA,NA,NA,NA```

<div dir="rtl">

اولین گزارش وزارت بهداشت آنچنان که در [آرشیو پایگاه اطلاع رسانی](https://behdasht.gov.ir/%D8%A7%D8%AE%D8%A8%D8%A7%D8%B1) آمده به تاریخ ۳۰ بهمن ماه ([گزارش ظهر](https://behdasht.gov.ir/%D8%A7%D8%AE%D8%A8%D8%A7%D8%B1/-----%D9%86%D8%AA%D8%A7%DB%8C%D8%AC-%D8%A2%D8%B2%D9%85%D8%A7%DB%8C%D8%B4-%D8%A7%D9%88%D9%84%DB%8C%D9%87-%D8%AF%D9%88-%D9%85%D9%88%D8%B1%D8%AF-%D9%85%D8%B4%DA%A9%D9%88%DA%A9-%D8%A8%D9%87-%D8%A7%D8%A8%D8%AA%D9%84%D8%A7-%DA%A9%D8%B1%D9%88%D9%86%D8%A7%D9%88%DB%8C%D8%B1%D9%88%D8%B3%D8%8C-%D9%85%D8%AB%D8%A8%D8%AA-%DA%AF%D8%B2%D8%A7%D8%B1%D8%B4-%D8%B4%D8%AF%D9%87-%D8%A7%D8%B3%D8%AA%E2%81%84--%D8%A2%D8%B2%D9%85%D8%A7%DB%8C%D8%B4%D8%A7%D8%AA-%D8%A8%D8%B1%D8%A7%DB%8C-%D9%82%D8%B7%D8%B9%DB%8C%D8%AA-%D8%AA%D8%B4%D8%AE%DB%8C%D8%B5-%D8%AF%D8%B1-%D8%AD%D8%A7%D9%84-%D8%A7%D9%86%D8%AC%D8%A7%D9%85-%D8%A7%D8%B3%D8%AA) - [گزارش شبانگاهی](https://behdasht.gov.ir/%D8%A7%D8%AE%D8%A8%D8%A7%D8%B1/%D9%81%D9%88%D8%AA-%D8%AF%D9%88-%D8%A8%DB%8C%D9%85%D8%A7%D8%B1-%D9%85%D8%A8%D8%AA%D9%84%D8%A7-%D8%A8%D9%87-%DA%A9%D8%B1%D9%88%D9%86%D8%A7%D9%88%DB%8C%D8%B1%D9%88%D8%B3-%D8%AC%D8%AF%DB%8C%D8%AF-%D8%AF%D8%B1-%D9%82%D9%85)) ارجاع دارد، در حالی که در [این فایل](https://github.com/smajidi/Iran-COVID-19-Data/blob/66eb22d569ae7da3aa2670b0c6720f969dc42142/Iran_Dailly_Covid19_Stat.csv) رکوردی برای ۲۹ بهمن نیز درج شده است.

</div>

‍‍```98/11/29,2/18/20,2,2,NA,NA,NA,0,0,NA,NA,NA,NA,NA,NA```

**Comment by smajidi** [comment]
سلام،

ممنون از توضیحاتتون. موارد ذکرشده بررسی و اصلاح شدند.
